version: 0.1
default:
  build:
    parameters:
      cached: 'true'
      parallel: 'true'

sandbox:
  deploy:
    parameters:
      parameter_overrides:
        - "CognitoUserPoolDomainName=andmoredev-sandbox"

qa:
  deploy:
    parameters:
      parameter_overrides:
        - "CognitoUserPoolDomainName=andmoredev-qa"

prod:
  deploy:
    parameters:
      parameter_overrides:
        - "CognitoUserPoolDomainName=andmoredev"
